# .github/workflows/deploy-firmware.yml (Versi Final)

name: Build and Deploy Firmware

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PlatformIO
      run: pip install -U platformio

    - name: Build PlatformIO Project
      run: pio run

    - name: Get Version Info
      id: version_info
      run: |
        VERSION_TAG=$(git describe --tags --abbrev=0)
        RELEASE_NOTES=$(git log -1 --pretty=%B | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
        FIRMWARE_URL="${{ secrets.SUPABASE_URL }}/storage/v1/object/firmware/firmware.bin"
        echo "version=${VERSION_TAG}" >> $GITHUB_OUTPUT
        echo "notes=${RELEASE_NOTES}" >> $GITHUB_OUTPUT
        echo "url=${FIRMWARE_URL}" >> $GITHUB_OUTPUT

    - name: Upload Firmware to Supabase Storage
      run: |
        FIRMWARE_PATH=$(find .pio/build -name "firmware.bin" | head -n 1)
        curl -X POST \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Content-Type: application/octet-stream" \
          -H "x-upsert: true" \
          --data-binary "@$FIRMWARE_PATH" \
          "${{ steps.version_info.outputs.url }}"
    
    - name: Insert Version Record into Supabase Database
      run: |
        curl -X POST \
          "${{ secrets.SUPABASE_URL }}/rest/v1/firmware_versions" \
          -H "apikey: ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "version": "${{ steps.version_info.outputs.version }}",
                "release_notes": "${{ steps.version_info.outputs.notes }}",
                "file_url": "${{ steps.version_info.outputs.url }}"
              }'